### ISSUE TITLE
Exception when charset is `nil`

### ISSUE THREAD

**Issue by rickychilcott** [gurgeous/httpdisk#3]
Thanks for this gem. It's been super helpful in a scraping project I've been fiddling with this weekend.

An Exception will get raised when charset is nil, even when `utf8: true` option is enabled. For example when `Content-Type: text/xml` as in https://s3.amazonaws.com/irs-form-990/201932849349300103_public.xml

There are several ways to handle this, I'm not sure your preference, but likely changing https://github.com/gurgeous/httpdisk/blob/ed8086375510baba21b3431a4909bd0766a7c802/lib/httpdisk/client.rb#L145 to be only run `if content_type && content_type.charset`. Alternatively, we could call `content_type.charset.to_s` and the code path should raise an `ArgumentError (unknown encoding name - )`

I'm happy to do a PR, but maybe it's simple enough for your to take a quick peak.

Thanks!

**Comment by gurgeous** [comment]
Thanks for the bug report! I will fix this shortly. Glad you are liking httpdisk so far. It's out in the wild but I really haven't promoted it anywhere. Pleased to have a first user, honestly :)

**Comment by gurgeous** [comment]
This is fixed in 0.5.1 if you want to upgrade. Thanks again Ricky.

**Comment by rickychilcott** [comment]
Thank you! This is working great now.
