### ISSUE TITLE
uninitialized constant HTTPDisk::Cache::Tempfile

### ISSUE THREAD

**Issue by rickychilcott** [gurgeous/httpdisk#4]
```shell
➜  mm-sales-db git:(master) ✗ → gem install httpdisk
➜  mm-sales-db git:(master) ✗ → httpdisk https://s3.amazonaws.com/irs-form-990/201932849349300103_public.xml
httpdisk: uninitialized constant HTTPDisk::Cache::Tempfile
```

This also occurs when using the library directly. It's easy enough in my own project to `require 'tempfile'`, but it seems like httpdisk should require it itself.

Thanks!

**Comment by gurgeous** [comment]
Thanks for this one too. No idea why it was working without the `require`, both on my machine and CI. What Ruby/platform are you using?

**Comment by rickychilcott** [comment]
I'm on Mac OS and ran into the issue on Ruby 3.0.1
