### ISSUE TITLE
`httpdisk-grep` chokes on non-gzip files

### ISSUE THREAD

**Issue by rickychilcott** [gurgeous/httpdisk#5]
I was using `httpdisk-grep` to clean up some failures and ran into this issue.

```shell
httpdisk-grep -h "HTTPDISK 403"
httpdisk-grep: not in gzip format (.DS_Store) # << this is unexpected
rm -rf ./**/.DS_Store

httpdisk-grep -h "HTTPDISK 403"
httpdisk-grep: 809: unexpected token at ...
```

Are you OK with it changing to warn on non-gzip formats as opposed to exiting?

**Comment by gurgeous** [comment]
Yeah, I think I warning is fine. I'll catch that exception and print something. BTW, there is another option for grepping that I probably need to document. `ripgrep-all` with `--rga-accurate`.

**Comment by rickychilcott** [comment]
Thanks, Adam. It looks like this should work. I see you bumped the gem version, but maybe didn't get around to publishing the gem, no rush. I have a workaround, but the other updates have been working quite well.

**Comment by gurgeous** [comment]
I'm waiting patiently to see what you turn up next before bumping the release. This is great, keep 'em coming! 😄

**Comment by rickychilcott** [comment]
Ha. Will Do. My project is nearing an end, so I'm not sure I have many more.

I have one feature request that I'll document in an issue to consider -- but there is no rush.
